apiVersion: v1
kind: Service
metadata:
  name: statefulservice
  labels:
    app: statefulsetapp
spec:
  ports:
  - port: 80
    name: statefulsetapp
  clusterIP: None
  selector:
    app: statefulsetapp
